# fly.toml app configuration file generated for order-tracker on 2023-07-11T17:00:31-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "order-tracker"
primary_region = "gru"

[http_service]
  internal_port = 4444
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
